package GsInspectorPresenter;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.ILanguageAspect;
import jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor;
import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import GsInspectorPresenter.editor.EditorAspectDescriptorImpl;
import jetbrains.mps.smodel.runtime.StructureAspectDescriptor;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "329ed8d6-630b-448d-b0ad-d0e71fe3ca82(GsInspectorPresenter)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "GsInspectorPresenter";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("329ed8d6-630b-448d-b0ad-d0e71fe3ca82"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{"MPSGobstones"};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "5fc7fbcf-600c-4e71-90a5-07fc8406e227(GsInspectorPresenter#6564092901427105655)"));
  }
  @Override
  protected <T extends ILanguageAspect> T createAspect(Class<T> aspectClass) {
    if (aspectClass == BehaviorAspectDescriptor.class) {
      return (T) new GsInspectorPresenter.behavior.BehaviorAspectDescriptor();
    }
    if (aspectClass == EditorAspectDescriptor.class) {
      return (T) new EditorAspectDescriptorImpl();
    }
    if (aspectClass == StructureAspectDescriptor.class) {
      return (T) new GsInspectorPresenter.structure.StructureAspectDescriptor();
    }


    return super.createAspect(aspectClass);
  }
}
