package GsDesktopUI.view;

/*Generated by MPS */

import javax.swing.JComponent;
import JavaGobstones.models.Board;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.Color;
import JavaGobstones.models.Cell;

public class BoardRenderer {
  public static JComponent render(Board board) {
    JPanel jPanel = new JPanel();
    jPanel.setLayout(new GridLayout(board.columnCount(), board.rowCount()));
    jPanel.setBackground(new Color(255, 245, 155));
    for (int row = 0; row < board.rowCount(); row++) {
      for (int column = 0; column < board.columnCount(); column++) {
        renderCell(jPanel);
      }
    }

    return jPanel;
  }

  public static void renderCell(JPanel container) {
    Cell cell = new Cell(0, 0);
    cell.addStones(JavaGobstones.models.Color.blue, 1);
    cell.addStones(JavaGobstones.models.Color.red, 1);
    cell.addStones(JavaGobstones.models.Color.black, 1);
    cell.addStones(JavaGobstones.models.Color.green, 1);
    CellView cellView = new CellView(cell);
    container.add(cellView);
  }
}
