package GsDesktopUI.view;

/*Generated by MPS */

import javax.swing.JComponent;
import JavaGobstones.models.Board;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.Color;
import JavaGobstones.models.Cell;

public class BoardRenderer {
  public static JComponent render(Board board) {
    JPanel jPanel = new JPanel();
    jPanel.setLayout(new GridLayout(board.columnCount(), board.rowCount()));
    if (!(board.isExploded())) {
      jPanel.setBackground(new Color(255, 245, 155));
    } else {
      jPanel.setBackground(Color.RED);
    }

    for (int row = 0; row < board.rowCount(); row++) {
      for (int column = 0; column < board.columnCount(); column++) {
        renderCell(jPanel, board.cellAt(column, row));
      }
    }

    return jPanel;
  }

  public static void renderCell(JPanel container, Cell cell) {
    CellView cellView = new CellView(cell);
    container.add(cellView);
  }
}
