package GsDesktopUI.view;

/*Generated by MPS */

import javax.swing.JComponent;
import JavaGobstones.models.Cell;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;

public class CellView extends JComponent {

  private final Cell cell;

  @Override
  protected void paintComponent(Graphics graphics) {
    super.paintComponent(graphics);
    if (cell != null) {
      if (cell.getRed() > 0) {
        graphics.setColor(Color.red);
        graphics.fillOval(4, 4, 18, 18);
      }
      if (cell.getBlack() > 0) {
        graphics.setColor(Color.black);
        graphics.fillOval(24, 4, 18, 18);
      }
      if (cell.getBlue() > 0) {
        graphics.setColor(Color.blue);
        graphics.fillOval(4, 24, 18, 18);
      }
      if (cell.getGreen() > 0) {
        graphics.setColor(Color.green);
        graphics.fillOval(24, 24, 18, 18);
      }
    }
  }
  @Override
  public Dimension getPreferredSize() {
    return new Dimension(48, 48);
  }

  public CellView() {
    this(null);
  }

  public CellView(Cell cell1) {
    cell = cell1;
    this.setBorder(BorderFactory.createLineBorder(((cell != null && cell.isSelected()) ? Color.BLACK : Color.WHITE)));
  }
}
