package GsDesktopUI.view;

/*Generated by MPS */

import javax.swing.JPanel;
import org.jetbrains.mps.openapi.model.SNode;
import java.awt.Graphics;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import java.awt.Dimension;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

public final class PreviewFactory {

  public static JPanel createPanel(final SNode thisCanvas) {
    return new JPanel() {
      @Override
      protected void paintComponent(final Graphics graphics) {
        super.paintComponent(graphics);
        SNodeOperations.getModel(thisCanvas).getRepository().getModelAccess().runReadAction(new Runnable() {
          public void run() {
            BehaviorReflection.invokeNonVirtual(Void.class, thisCanvas, "GsInspectorPresenter.structure.MainProgram", "call_renderTable_6564092901427030088", new Object[]{graphics});
          }
        });
      }

      @Override
      public Dimension getPreferredSize() {
        return new Dimension(500, 500);
      }

      @Override
      public Border getBorder() {
        return new TitledBorder("Tablero Final");
      }
    };
  }
}
