package BoardWindowTool.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;

public class BoardWindowTool_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("BoardWindowTool");
  public BoardWindowTool_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new OpenBoardInterpreter_Action());
    // groups 
  }
}
