package BoardWindowTool.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindowAnchor;
import javax.swing.JComponent;
import javax.swing.JScrollPane;
import javax.swing.JPanel;

public class BoardInterpreter_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  public BoardInterpreter_Tool(Project project) {
    super(project, "Tablero", -1, ICON, ToolWindowAnchor.RIGHT, false);
  }
  public JComponent getComponent() {
    return new JScrollPane(new JPanel());
  }
}
