package BoardWindowTool.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.custom.BaseCustomProjectPlugin;
import jetbrains.mps.project.MPSProject;

public class GobstonesBoard_CustomProjectPlugin extends BaseCustomProjectPlugin {
  public GobstonesBoard_CustomProjectPlugin() {
  }
  public void doInit(MPSProject project) {
  }
}
