package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;
import org.jetbrains.mps.openapi.language.SConcept;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class BinaryOperation_BehaviorDescriptor extends Expression_BehaviorDescriptor implements BinaryLike_BehaviorDescriptor {
  public boolean virtual_canPropagateUnmatchedParenUp_1742226163722653670(SNode __thisNode__, SNode leaf, boolean rightParen) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public int virtual_getPriority_1262430001741497858(SConcept __thisConcept__) {
    return DefaultValuesHolder.defaultValue(Integer.TYPE);
  }
  public SNode virtual_getSyntacticallyLeftSideExpression_6035600022472704037(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_getSyntacticallyRightSideExpression_6035600022472710269(SNode __thisNode__) {
    return null;
  }
  public void virtual_setSyntacticallyLeftSideExpression_6035600022472727417(SNode __thisNode__, SNode expr) {
  }
  public void virtual_setSyntacticallyRightSideExpression_1742226163722653694(SNode __thisNode__, SNode expr) {
  }

  @Override
  public String getConceptFqName() {
    return "MPSGobstones.structure.BinaryOperation";
  }

}
