package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import JavaGobstones.models.Board;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class BoardDefinition_Behavior {
  public static int call_maxRowLength_9156895335219502540(SNode __thisNode__) {
    return BoardDefinition__BehaviorDescriptor.maxRowLength_id7WjOWF5c9Rc(__thisNode__);
  }
  public static void call_synchronizeColumnsSize_9156895335219526515(SNode __thisNode__, int desiredSize) {
    BoardDefinition__BehaviorDescriptor.synchronizeColumnsSize_id7WjOWF5cfHN(__thisNode__, desiredSize);
  }
  public static void call_synchronizeRowsSize_9156895335219648452(SNode __thisNode__, int desiredSize) {
    BoardDefinition__BehaviorDescriptor.synchronizeRowsSize_id7WjOWF5cHv4(__thisNode__, desiredSize);
  }
  public static Board call_generateBoard_6321380926643643272(SNode __thisNode__) {
    return BoardDefinition__BehaviorDescriptor.generateBoard_id5uU3BnIxye8(__thisNode__);
  }
}
