package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.SortedSet;
import JavaGobstones.models.Cell;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class BoardRowDefinition_Behavior {
  public static void call_addCells_9156895335219619911(SNode __thisNode__, int amount) {
    BoardRowDefinition__BehaviorDescriptor.addCells_id7WjOWF5cAx7(__thisNode__, amount);
  }
  public static void call_removeLast_9156895335219629430(SNode __thisNode__, int amount) {
    BoardRowDefinition__BehaviorDescriptor.removeLast_id7WjOWF5cCPQ(__thisNode__, amount);
  }
  public static SortedSet<Cell> call_generateRow_9156895335219914157(SNode __thisNode__, int y) {
    return BoardRowDefinition__BehaviorDescriptor.generateRow_id7WjOWF5dImH(__thisNode__, y);
  }
}
