package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class BooleanType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public SNode virtual_getBoxedType_1213877337320(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "MPSGobstones.structure.BooleanType";
  }

}
