package MPSGobstones.behavior;

/*Generated by MPS */

import JavaGobstones.models.Cell;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class CellDefinition_Behavior {
  public static Cell call_generateCell_9156895335219903846(SNode __thisNode__, int x, int y) {
    return CellDefinition__BehaviorDescriptor.generateCell_id7WjOWF5dFPA(__thisNode__, x, y);
  }
}
