package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class Comparision_BehaviorDescriptor extends BinaryOperation_BehaviorDescriptor {
  public InterpreterValue virtual_reduce_2998821801951249132(SNode __thisNode__, InterpreterState state) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "MPSGobstones.structure.Comparision";
  }

  public abstract boolean virtual_compare_2998821801951353394(SNode __thisNode__, int leftValue, int rightValue);
}
