package MPSGobstones.behavior;

/*Generated by MPS */

import JavaGobstones.models.Color;
import JavaGobstones.models.Direction;

public class InterpreterConstants {

  /**
   * This class exists mainly for performance reasons and aims to avoid instantiating 
   * unnecesary interpreter values for model constants
   */
  public static final InterpreterValue TRUE = new InterpreterValue(InterpreterValueType.BOOLEAN, true);
  public static final InterpreterValue FALSE = new InterpreterValue(InterpreterValueType.BOOLEAN, false);

  public static final InterpreterValue BLUE = new InterpreterValue(InterpreterValueType.COLOR, Color.blue);
  public static final InterpreterValue BLACK = new InterpreterValue(InterpreterValueType.COLOR, Color.black);
  public static final InterpreterValue RED = new InterpreterValue(InterpreterValueType.COLOR, Color.red);
  public static final InterpreterValue GREEN = new InterpreterValue(InterpreterValueType.COLOR, Color.green);

  public static final InterpreterValue NORTH = new InterpreterValue(InterpreterValueType.DIRECTION, Direction.north);
  public static final InterpreterValue EAST = new InterpreterValue(InterpreterValueType.DIRECTION, Direction.east);
  public static final InterpreterValue WEST = new InterpreterValue(InterpreterValueType.DIRECTION, Direction.west);
  public static final InterpreterValue SOUTH = new InterpreterValue(InterpreterValueType.DIRECTION, Direction.south);

  public static InterpreterValue from(Color color) {
    switch (color) {
      case blue:
        return BLUE;
      case black:
        return BLACK;
      case red:
        return RED;
      case green:
        return GREEN;
      default:
        throw new RuntimeException("matching color fatal error");
    }
  }
  public static InterpreterValue from(Direction direction) {
    switch (direction) {
      case north:
        return NORTH;
      case east:
        return EAST;
      case west:
        return WEST;
      case south:
        return SOUTH;
      default:
        throw new RuntimeException("matching direction fatal error");
    }
  }
}
