package MPSGobstones.behavior;

/*Generated by MPS */


public class InterpreterValue {
  public final InterpreterValueType type;
  public final Object value;

  public InterpreterValue(InterpreterValueType type, Object value) {
    this.type = type;
    this.value = value;
  }
}
