package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Program_Behavior {
  public static InterpreterState call_interpret_6044724656164062582(SNode __thisNode__, InterpreterState state) {
    return Program__BehaviorDescriptor.interpret_id5fzbgLBH4lQ(__thisNode__, state);
  }
}
