package MPSGobstones.behavior;

/*Generated by MPS */

import java.util.Map;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class RoutineInvocation_Behavior {
  public static Map<String, InterpreterValue> call_initializeParameterVariables_9156895335216165469(SNode __thisNode__, InterpreterState state) {
    return RoutineInvocation__BehaviorDescriptor.initializeParameterVariables_id7WjOWF4Zr9t(__thisNode__, state);
  }
}
