package MPSGobstones.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class Statement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public InterpreterState virtual_interpret_1082824515535573731(SNode __thisNode__, InterpreterState state) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "MPSGobstones.structure.Statement";
  }

}
