package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class StatementList_Behavior {
  public static void call_interpretEach_2998821801951649029(SNode __thisNode__, InterpreterState state) {
    StatementList__BehaviorDescriptor.interpretEach_id2AtX8Dq1_O5(__thisNode__, state);
  }
}
