package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class True_BehaviorDescriptor extends BooleanLiteral_BehaviorDescriptor {
  public InterpreterValue virtual_reduce_2998821801951249132(SNode __thisNode__, InterpreterState state) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "MPSGobstones.structure.True";
  }

}
