package MPSGobstones.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class WhileStatement_BehaviorDescriptor extends LoopStatement_BehaviorDescriptor implements CanBeRestricted_BehaviorDescriptor {
  public InterpreterState virtual_interpret_1082824515535573731(SNode __thisNode__, InterpreterState state) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "MPSGobstones.structure.WhileStatement";
  }

}
