package MPSGobstones.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0xa107f9943a8201dL, "MPSGobstones.structure.BinaryOperation"))) {
        return Collections.<ConceptEditor>singletonList(new BinaryOperation_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x7f13d3cac51f62a7L, "MPSGobstones.structure.BoardDefinition"))) {
        return Collections.<ConceptEditor>singletonList(new BoardDefinition_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x7f13d3cac52c7b77L, "MPSGobstones.structure.BoardRowDefinition"))) {
        return Collections.<ConceptEditor>singletonList(new BoardRowDefinition_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0xa107f9943a7f180L, "MPSGobstones.structure.BooleanLiteral"))) {
        return Collections.<ConceptEditor>singletonList(new BooleanLiteral_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x7f13d3cac5200080L, "MPSGobstones.structure.CellDefinition"))) {
        return Collections.<ConceptEditor>singletonList(new CellDefinition_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x2ab0def7b5610a42L, "MPSGobstones.structure.Color"))) {
        return Collections.<ConceptEditor>singletonList(new Color_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x2ab0def7b5614da9L, "MPSGobstones.structure.Direction"))) {
        return Collections.<ConceptEditor>singletonList(new Direction_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x7f13d3cac4f69cb5L, "MPSGobstones.structure.FunctionDeclaration"))) {
        return Collections.<ConceptEditor>singletonList(new FunctionDeclaration_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x7f13d3cac4f69cb6L, "MPSGobstones.structure.FunctionInvocation"))) {
        return Collections.<ConceptEditor>singletonList(new FunctionInvocation_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x6b36268ffc4fb929L, "MPSGobstones.structure.IfElseStatement"))) {
        return Collections.<ConceptEditor>singletonList(new IfElseStatement_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x618424b489a43df6L, "MPSGobstones.structure.IntegerLiteral"))) {
        return Collections.<ConceptEditor>singletonList(new IntegerLiteral_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x57ba0e75ee9239d1L, "MPSGobstones.structure.Library"))) {
        return Collections.<ConceptEditor>singletonList(new Library_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x7f13d3cac51bb110L, "MPSGobstones.structure.NativeFunction"))) {
        return Collections.<ConceptEditor>singletonList(new NativeFunction_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x673143db71a8be45L, "MPSGobstones.structure.NativeProcedure"))) {
        return Collections.<ConceptEditor>singletonList(new NativeProcedure_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x618424b489a40ba1L, "MPSGobstones.structure.ParenthesisExpression"))) {
        return Collections.<ConceptEditor>singletonList(new ParenthesisExpression_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x332b7c31ccbf9e41L, "MPSGobstones.structure.ProcedureDeclaration"))) {
        return Collections.<ConceptEditor>singletonList(new ProcedureDeclaration_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x332b7c31ccc227d8L, "MPSGobstones.structure.ProcedureInvocation"))) {
        return Collections.<ConceptEditor>singletonList(new ProcedureInvocation_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0xa107f9943a58e1dL, "MPSGobstones.structure.Program"))) {
        return Collections.<ConceptEditor>singletonList(new Program_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x379454b04a7864c4L, "MPSGobstones.structure.RepeatStatement"))) {
        return Collections.<ConceptEditor>singletonList(new RepeatStatement_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0xa107f9943a750c2L, "MPSGobstones.structure.StatementList"))) {
        return Collections.<ConceptEditor>singletonList(new StatementList_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x618424b489a2abd5L, "MPSGobstones.structure.Type"))) {
        return Collections.<ConceptEditor>singletonList(new Type_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x618424b489a3cd9fL, "MPSGobstones.structure.UnaryNot"))) {
        return Collections.<ConceptEditor>singletonList(new UnaryNot_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x299df48a5a06b9ceL, "MPSGobstones.structure.VariableAssignment"))) {
        return Collections.<ConceptEditor>singletonList(new VariableAssignment_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x32ccd531a47ba7f6L, "MPSGobstones.structure.VariableName"))) {
        return Collections.<ConceptEditor>singletonList(new VariableName_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0x379454b04a788182L, "MPSGobstones.structure.WhileStatement"))) {
        return Collections.<ConceptEditor>singletonList(new WhileStatement_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
