package MPSGobstones.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0xa107f9943a750c2L) {
      return new StatementList_Constraints();
    }
    if (id == 0x332b7c31ccc227d8L) {
      return new ProcedureInvocation_Constraints();
    }
    if (id == 0x7f13d3cac4fa27ddL) {
      return new RoutineInvocation_Constraints();
    }
    if (id == 0xa107f9943a750c1L) {
      return new Statement_Constraints();
    }
    if (id == 0x673143db71a8be45L) {
      return new NativeProcedure_Constraints();
    }
    if (id == 0x53c2c23e11d53505L) {
      return new VariableReference_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
}
