package MPSGobstones.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StatementList_Constraints extends BaseConstraintsDescriptor {
  public StatementList_Constraints() {
    super(MetaIdFactory.conceptId(0xcb8c78e791643a8L, 0x8d8ea292ead7a894L, 0xa107f9943a750c2L));
  }
}
