package JavaGobstones.models;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;
import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import gnu.trove.decorator.TObjectIntHashMapDecorator;
import gnu.trove.TObjectIntHashMap;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.IMapping;

public class Cell {
  public final Tuples._2<Integer, Integer> pos;

  public final Map<Color, Integer> stones = MapSequence.<Color>fromMapAndKeysArray(new TObjectIntHashMapDecorator(new TObjectIntHashMap<Color>()), Color.blue, Color.black, Color.red, Color.green).withValues(0, 0, 0, 0);

  public boolean isEmpty() {
    return MapSequence.fromMap(stones).all(new IWhereFilter<IMapping<Color, Integer>>() {
      public boolean accept(IMapping<Color, Integer> color) {
        return color.value() <= 0;
      }
    });
  }
  public Cell(Tuples._2<Integer, Integer> pos) {
    this.pos = pos;
  }
}
