package JavaGobstones.models;

/*Generated by MPS */


public enum Color implements Order<Color> {
  blue() {
    public Color prev() {
      return Color.green;
    }
    public Color next() {
      return Color.black;
    }

  },
  black() {
    public Color prev() {
      return Color.blue;
    }
    public Color next() {
      return Color.red;
    }

  },
  red() {
    public Color prev() {
      return Color.black;
    }
    public Color next() {
      return Color.green;
    }

  },
  green() {
    public Color prev() {
      return Color.red;
    }
    public Color next() {
      return Color.blue;
    }

  };

}
