package JavaGobstones.models;

/*Generated by MPS */


public enum Direction implements Order<Direction> {
  west() {
    public Direction prev() {
      return Direction.south;
    }
    public Direction next() {
      return Direction.north;
    }

  },
  north() {
    public Direction prev() {
      return Direction.west;
    }
    public Direction next() {
      return Direction.east;
    }

  },
  east() {
    public Direction prev() {
      return Direction.north;
    }
    public Direction next() {
      return Direction.south;
    }

  },
  south() {
    public Direction prev() {
      return Direction.east;
    }
    public Direction next() {
      return Direction.west;
    }

  };

}
