package JavaGobstones.models;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;

public enum Direction implements Order<Direction> {
  west(MultiTuple.<Integer,Integer>from(-1, 0)) {
    public Direction next() {
      return Direction.south;
    }
    public Direction prev() {
      return Direction.north;
    }

  },
  north(MultiTuple.<Integer,Integer>from(0, -1)) {
    public Direction prev() {
      return Direction.west;
    }
    public Direction next() {
      return Direction.east;
    }

  },
  east(MultiTuple.<Integer,Integer>from(1, 0)) {
    public Direction prev() {
      return Direction.north;
    }
    public Direction next() {
      return Direction.south;
    }

  },
  south(MultiTuple.<Integer,Integer>from(0, 1)) {
    public Direction prev() {
      return Direction.east;
    }
    public Direction next() {
      return Direction.west;
    }

  };

  Direction(Tuples._2<Integer, Integer> vector) {
    this.vector = vector;
  }

  private final Tuples._2<Integer, Integer> vector;

  public Tuples._2<Integer, Integer> move(Tuples._2<Integer, Integer> position) {
    return MultiTuple.<Integer,Integer>from((int) vector._0() + (int) position._0(), (int) vector._1() + (int) position._1());
  }

}
