package GsInspectorPresenter.behavior;

/*Generated by MPS */

import MPSGobstones.behavior.BoardDefinition_BehaviorDescriptor;

public class BoardDeclaration_BehaviorDescriptor extends BoardDefinition_BehaviorDescriptor {
  public BoardDeclaration_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GsInspectorPresenter.structure.BoardDeclaration";
  }
}
