package GsInspectorPresenter.behavior;

/*Generated by MPS */

import MPSGobstones.behavior.Library_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class LibraryDeclaration_BehaviorDescriptor extends Library_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "GsInspectorPresenter.structure.LibraryDeclaration";
  }

}
