package GsInspectorPresenter.behavior;

/*Generated by MPS */

import MPSGobstones.behavior.Library_BehaviorDescriptor;

public class LibraryDeclaration_BehaviorDescriptor extends Library_BehaviorDescriptor {
  public LibraryDeclaration_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GsInspectorPresenter.structure.LibraryDeclaration";
  }
}
