package GsInspectorPresenter.behavior;

/*Generated by MPS */

import MPSGobstones.behavior.Program_BehaviorDescriptor;

public class MainProgram_BehaviorDescriptor extends Program_BehaviorDescriptor {
  public MainProgram_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GsInspectorPresenter.structure.MainProgram";
  }
}
