package GsInspectorPresenter.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.awt.Graphics;
import java.awt.Color;

public class MainProgram_Behavior {
  public static void init(SNode thisNode) {
  }
  public static void call_renderTable_6564092901427030088(SNode thisNode, Graphics graphics) {
    graphics.setColor(Color.RED);
    graphics.fillOval(20, 20, 60, 60);
  }
}
