package GsInspectorPresenter.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import JavaGobstones.models.Board;

public class MainProgram_Behavior {
  public static void init(SNode thisNode) {
  }
  public static Board call_interpret_6564092901427030088(SNode thisNode) {
    Board board = new Board();
    return board;
  }
}
