package GsInspectorPresenter.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ResultBoard_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ResultBoard_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GsInspectorPresenter.structure.ResultBoard";
  }
}
