package GsInspectorPresenter.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class WhileStatementRestriction_BehaviorDescriptor extends FeatureRestriction_BehaviorDescriptor {
  public boolean virtual_isRestricted_6035600022472214347(SNode __thisNode__, SNode node) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }

  @Override
  public String getConceptFqName() {
    return "GsInspectorPresenter.structure.WhileStatementRestriction";
  }

}
